### PR TITLE
Fix dashboard having no payments

### LINKED ISSUE #199: Dashboard crashes when new user has no payments
**Describe the bug**
New user doesn't have any payments, the state for 'payments' in the Payment component is undefined, tries to read the length of 'payments' which leads page to crash and show error.

Very similar to bug #171 but introduced for the dashboard payments due to PR #184.

**Severity**
Major error, cannot open dashboard page

**To Reproduce**
1. Create a new user
2. Go to the dashboard
3. See error - screenshot attached below

**Expected behaviour**
User should be able to view their dashboard and see no payments.

**Actual behaviour**
A clear and concise description of what you actually to happened.

**Screenshots**

**Environment:**
* OS: Windows 10
* Browser: Chrome

**Possible solution:**
Apply similar fix as #171 (PR#179)

**Additional context**

### PR DESCRIPTION
**Pull request by williamlixu**
## Pull Request Information
Closes #199

**What is the PR Type:** 
* Bug fix

**Describe the added/fixed behaviour:**
* Fixed bug where new users checking dashboard will give an error.
* This undefined error is caused by the API returning 404 not found thus render resultant body data as undefined.
* Fixed in the same way as in #179

## Checklist

- [x] Pull request has suitable title, adequately described and associated with a github issue
- [x] Branch name follows correct convention (e.g. feature/[id]-some-feature)
- [x] Branch builds and executes with no errors
- [ ] Test cases has been generated for the feature and test cases pass
- [x] Updated relevant wiki/documentation - (no docs needed)

### CODE REVIEW

File: Frontend/frontend/src/Components/DashboardPayments.js [hunk 1]
```diff
@@ -44,13 +46,14 @@ export default class DashboardPayments extends Component {
...
         const payments = this.state.payments;
+        const paymentComponents = [];
         const contributorsPayments = this.state.contributionPayments;
-        for (let i = 0; i < this.state.payments.length; i++) {
+
+        for (let i = 0; i < payments.length; i++) {
             const paymentData = payments[i];
             const contributors = contributorsPayments[i];
-            paymentComponenets.push(
+            paymentComponents.push(
```
Comment (dder725) [inline Frontend/frontend/src/Components/DashboardPayments.js]: Nice touch! 😄
